In [ ]:
# feature 가 많아지면 예측도가 좋아진다.

In [ ]:
#H(x1,x2,x3) = x1w1 + x2w2 + x3w3

In [1]:
import tensorflow as tf
import numpy as np

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

tf.model = tf.keras.Sequential()

tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3))  # input_dim=3 gives multi-variable regression
tf.model.add(tf.keras.layers.Activation('linear'))  # this line can be omitted, as linear activation is default
# advanced reading https://towardsdatascience.com/activation-functions-neural-networks-1cbd9f8d91d6

tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()
history = tf.model.fit(x_data, y_data, epochs=100)

y_predict = tf.model.predict(np.array([[72., 93., 90.]]))
print(y_predict)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 4         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________
Train on 5 samples
Epoch 1/100
5/5 [==============================] - 0s 46ms/sample - loss: 18546.7344
Epoch 2/100
5/5 [==============================] - 0s 1ms/sample - loss: 5821.3174
Epoch 3/100
5/5 [==============================] - 0s 2ms/sample - loss: 1832.5706
Epoch 4/100
5/5 [==============================] - 0s 2ms/sample - loss: 582.3069
Epoch 5/100
5/5 [==============================] - 0s 1ms/sample - loss: 190.4115
Epoch 6/100
5/5 [==============================] - 0s 1ms/sample - loss: 67.5696
Epoch 7/1

Epoch 94/100
5/5 [==============================] - 0s 1ms/sample - loss: 11.0183
Epoch 95/100
5/5 [==============================] - 0s 1ms/sample - loss: 11.0131
Epoch 96/100
5/5 [==============================] - 0s 1ms/sample - loss: 11.0079
Epoch 97/100
5/5 [==============================] - 0s 997us/sample - loss: 11.0027
Epoch 98/100
5/5 [==============================] - 0s 2ms/sample - loss: 10.9975
Epoch 99/100
5/5 [==============================] - 0s 1ms/sample - loss: 10.9923
Epoch 100/100
5/5 [==============================] - 0s 1ms/sample - loss: 10.9871
[[166.67061]]


In [11]:
history

In [ ]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('../data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# data output
'''
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 ...
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 ...
 [149.]
 [192.]] 
y_data shape: (25, 1)
'''
tf.model = tf.keras.Sequential()
# activation function doesn't have to be added as a separate layer. Add it as an argument of Dense() layer
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))
# tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.summary()

tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
history = tf.model.fit(x_data, y_data, epochs=2000)

# Ask my score
print("Your score will be ", tf.model.predict([[100, 70, 101]]))
print("Other scores will be ", tf.model.predict([[60, 70, 110], [90, 100, 80]]))